// Cloudflare Turnstile — server-side token verification.
// Docs: https://developers.cloudflare.com/turnstile/get-started/server-side-validation/
//
// Tokens generated by the client widget must be verified server-side against
// this endpoint. Each token is single-use and expires after ~5 minutes.

const VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify";

interface TurnstileVerifyResponse {
  success: boolean;
  challenge_ts?: string;
  hostname?: string;
  "error-codes"?: string[];
  action?: string;
  cdata?: string;
}

export interface TurnstileResult {
  success: boolean;
  errorCodes?: string[];
  hostname?: string;
}

/**
 * Verifies a Turnstile token against Cloudflare. Returns success + metadata.
 * Fails-closed: if TURNSTILE_SECRET_KEY is missing or the fetch errors,
 * the call is rejected (success=false). This is intentional — any charge
 * endpoint should refuse to process payments when the captcha gate is
 * misconfigured, since it is an anti-fraud control.
 */
export async function verifyTurnstile(
  token: string,
  remoteIp?: string,
): Promise<TurnstileResult> {
  const secret = process.env.TURNSTILE_SECRET_KEY;
  if (!secret) {
    console.error("[turnstile] TURNSTILE_SECRET_KEY not configured");
    return { success: false, errorCodes: ["missing-secret"] };
  }
  if (!token) {
    return { success: false, errorCodes: ["missing-input-response"] };
  }

  try {
    const form = new URLSearchParams();
    form.set("secret", secret);
    form.set("response", token);
    if (remoteIp) form.set("remoteip", remoteIp);

    const res = await fetch(VERIFY_URL, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: form.toString(),
    });

    const data = (await res.json()) as TurnstileVerifyResponse;

    if (!data.success) {
      console.warn(
        "[turnstile] verification failed:",
        data["error-codes"]?.join(",") ?? "unknown",
      );
    }

    return {
      success: data.success === true,
      errorCodes: data["error-codes"],
      hostname: data.hostname,
    };
  } catch (err) {
    console.error("[turnstile] verify request failed:", err);
    return { success: false, errorCodes: ["internal-error"] };
  }
}
